apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: docdb-mongo-uri
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "travelmemory/docdb-mongo-uri"
        objectType: "secretsmanager"
        jmesPath:
          - path: "MONGO_URI"
            objectAlias: "MONGO_URI"
  secretObjects:
    - secretName: docdb-mongo-uri-k8s
      type: Opaque
      data:
        - objectName: "MONGO_URI"
          key: MONGO_URI
